openapi: 3.0.0
info:
  title: "${project.artifactId} ${project.version} (${git.commit.id.abbrev})"
  description: Example application
  contact:
    name: "Caspar Derksen"
    url: https://github.com/casparderksen/docker-thorntail-jee8-microprofile
  license:
    name: Eclipse Public License - v 2.0
    url: https://www.eclipse.org/legal/epl-v20.html
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /health:
    description: "MicroProfile Health endpoint"
  /metrics:
    description: "MicroProfile Metrics endpoint"
  /openapi:
    description: "OpenAPI endpoint"
